# Generated by Django 4.0.4 on 2022-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingID', models.CharField(max_length=6)),
                ('invoice_no', models.IntegerField(blank=True, default=0, null=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('item_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('status', models.CharField(max_length=50)),
                ('shipper_name', models.CharField(max_length=50)),
                ('receiver_address', models.CharField(max_length=100)),
                ('shipment_type', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('pickup', models.CharField(max_length=50)),
            ],
        ),
    ]
