# Generated by Django 4.0.4 on 2022-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='item_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='picture'),
        ),
    ]
