# Generated by Django 4.0.4 on 2022-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_track_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='item_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='ItemImage'),
        ),
    ]
