# Generated by Django 4.0.4 on 2022-04-20 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_track_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='track',
            name='pickup',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='receiver_address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='status',
            field=models.IntegerField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='trackingID',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
